// @ts-check

// See: https://docusaurus.io/docs/sidebar
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lockSidebar: [
    {
      type: "category",
      label: "Locks",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Locks",
        description: "This is an auto-generated list of all the locks.",
        slug: "upgrades/locks",
      },
      items: [{ type: "autogenerated", dirName: "upgrades/locks" }],
    },
  ],
  upgradeOtherSidebar: [
    {
      type: "category",
      label: "Other",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Other Upgrades",
        description:
          "This is an auto-generated list of all the upgrades which do not fit elsewhere.",
        slug: "upgrades/other",
      },
      items: [{ type: "autogenerated", dirName: "upgrades/other" }],
    },
  ],
  characterSidebar: [
    {
      type: "category",
      label: "Characters",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Characters",
        description:
          "This is an auto-generated list of characters in hackmud's storyline.",
        slug: "lore/characters",
      },
      items: [{ type: "autogenerated", dirName: "lore/characters" }],
    },
  ],
  userSidebar: [
    {
      type: "category",
      label: "Users",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Users",
        description:
          "This is an auto-generated list of notable users in the hackmud network.",
        slug: "lore/users",
      },
      items: [{ type: "autogenerated", dirName: "lore/users" }],
    },
  ],
  eventSidebar: [
    {
      type: "category",
      label: "Events",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Events",
        description: "This is an auto-generated list of all events.",
        slug: "lore/events",
      },
      items: [{ type: "autogenerated", dirName: "lore/events" }],
    },
  ],
  mechanicSidebar: [
    {
      type: "category",
      label: "Mechanics",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Mechanics",
        description: "This is an auto-generated list of all of hackmud's more esoteric mechanics",
        slug: "lore/mechanics",
      },
      items: [{ type: "autogenerated", dirName: "lore/mechanics" }],
    },
  ],
  trustScriptsSidebar: [
    {
      type: "category",
      label: "Trust Scripts",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Trust Scripts",
        description: "This is an auto-generated list of all trust scripts.",
        slug: "scripting/trust_scripts",
      },
      items: [{ type: "autogenerated", dirName: "scripting/trust_scripts" }],
    },
  ],
  miscGuidesSidebar: [
    {
      type: "category",
      label: "Misc",
      collapsible: false,
      link: {
        type: "generated-index",
        title: "Misc Guides",
        description: "This is an auto-generated list of miscellaneous guides.",
        slug: "guides/misc",
      },
      items: [{ type: "autogenerated", dirName: "guides/misc" }],
    },
  ],
};

module.exports = sidebars;